version: "3.7"

services:
  vapi:
    image: ecency/api:latest
    environment:
      - PRIVATE_API_ADDR
      - PRIVATE_API_AUTH
      - HIVESIGNER_SECRET
      - SEARCH_API_ADDR
      - SEARCH_API_SECRET
      - CHAINSTACK_API_KEY
      - CHAINZ_API_KEY
      - BLOCKSTREAM_CLIENT_ID
      - BLOCKSTREAM_CLIENT_SECRET
    restart: always
    ports:
      - "4000:4000"
    hostname: vapi
    networks:
      - vision

  web:
    image: ecency/vision-next:develop
    deploy:
      replicas: 4
    environment:
      - USE_PRIVATE
      - HIVESIGNER_SECRET
      - PLAUSIBLE_API_KEY
      - NEXT_PUBLIC_GMAPS_MAP_ID
      - NEXT_PUBLIC_GMAPS_API_KEY
      - MATTERMOST_BASE_URL
      - MATTERMOST_ADMIN_TOKEN
      - MATTERMOST_TEAM_ID
    restart: always
    ports:
      - "3000:3000"
    hostname: web
    networks:
      - vision

networks:
  vision:
    external: true
